// <auto-generated />
namespace QuanLySinhVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsinhvien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsinhvien));
        
        string IMigrationMetadata.Id
        {
            get { return "202111291901258_add sinhvien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
